### ISSUE TITLE
Possibly redundant code in server/web.js

### ISSUE THREAD

**Issue by Niklas81** [StephanHoyer/mithril-isomorphic-example#107]
What is the purpose if the lines `const render = module.render || (a => a)` and `.then(render)` in `server/web.js`? From what I can tell they do nothing, and removing them has no effect. Do they represent some technique that you meant to demonstrate, or are they simply some remnant of an older version?

**Comment by StephanHoyer** [comment]
route resolver can have a [render](https://mithril.js.org/route.html#routeresolverrender) callback

**Comment by StephanHoyer** [comment]
I just refactored the example to use `async`/`await`. Maybe it's now easier to understand

**Comment by Niklas81** [comment]
Ah, that makes sense! I actually really prefer ES5 syntax, simply knowing that `module.render` expects an export of a render method in router helps to clarify.

From what I can tell, the changes you made this morning are:
- Upgrade packages
- Adopt ES6 syntax
- Prettify
- Add async call with delay to `with-route-resolver.js`
Correct?

What are typical use cases there you would use an async call with a deley like that?
