### ISSUE TITLE
XSS on server-rendered HTML.

### ISSUE THREAD

**Issue by grumpi** [StephanHoyer/mithril-isomorphic-example#6]
I can trigger an XSS vulnerability through the server-rendered HTML.

Minimal example: https://github.com/grumpi/mithril-isomorphic-example/tree/xss

I've been looking at mithril-node-render, but I don't see where the problem is - it looks like you're escaping things thoroughly there.

**Comment by grumpi** [comment]
Ok, sorry about that, bumping the version on your mithril-node-render package to 0.4.1 solved the problem. The one that got installed with npm install didn't escape properly, but the newer one does.

**Comment by StephanHoyer** [comment]
Just updated the dependencies. Thanks for pointing this out.
